imports:
    - { resource: config_dev.yml }

anu_style_proxy:
    test: true
    process_resources: true
    style_server_base: http://localhost

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

#swiftmailer:
#    disable_delivery: true
