parameters:
    anu_style_proxy.asset_server_controller.class: ANU\Bundle\StyleProxyBundle\Controller\AssetServerController
    anu_style_proxy.cache_backend_assets: ~

services:
    anu_style_proxy.asset_server_controller:
        class: %anu_style_proxy.asset_server_controller.class%
        calls:
            - [ setContainer, [ @service_container ] ]
