parameters:
    anu_style_proxy.asset_server_controller.class: ANU\Bundle\StyleProxyBundle\Controller\AssetServerController
    anu_style_proxy.asset_server.class: ANU\Bundle\StyleProxyBundle\Proxy\AssetServer

services:
    anu_style_proxy.asset_server_controller:
        class: %anu_style_proxy.asset_server_controller.class%
        arguments: [ @anu_style_proxy.backend_base_url ]
        calls:
            - [ setContainer, [ @service_container ] ]
        scope: request
    anu_style_proxy.asset_server:
        class: %anu_style_proxy.asset_server.class%
        arguments: [ @orbt_resource_mirror.mirror ]
