parameters:
    anu_style_proxy.cache_profile_asset_preprocessor.class: ANU\Bundle\StyleProxyBundle\Preprocessor\CacheProfileAssetPreprocessor

services:
    anu_style_proxy.cache_profile_asset_preprocessor:
        class: %anu_style_proxy.cache_profile_asset_preprocessor.class%
        arguments:
            - @orbt_resource_mirror.mirror
            - %anu_style_proxy.backend_style_base%
            - %anu_style_proxy.backend_style_include%
        tags:
            - { name: anu_style_proxy.profile_preprocessor }
