anu_style_proxy_homepage:
    pattern:  /
    defaults: { _controller: anu_style_proxy.default_controller:indexAction }
anu_style_proxy_style_server:
    pattern:  /include.php
    defaults: { _controller: anu_style_proxy.style_server_controller:includeAction }
anu_style_proxy_asset_server:
    pattern:  /{path}
    defaults: { _controller: anu_style_proxy.asset_server_controller:resourceAction }
    requirements:
        path: "\d+/.+|images/.+|style_.+\.css"
anu_style_proxy_asset_redirect:
    pattern:  /{path}
    defaults: { _controller: anu_style_proxy.asset_server_controller:redirectAction }
    requirements:
        path: ".+"
