anu_style_proxy_homepage:
    pattern:  /
    defaults: { _controller: anu_style_proxy.default_controller:indexAction }
anu_style_proxy_style_server:
    pattern:  /include.php
    defaults: { _controller: anu_style_proxy.style_server_controller:includeAction }
anu_style_proxy_asset_server:
    pattern:  /{path}
    defaults: { _controller: anu_style_proxy.asset_server_controller:resourceAction }
    requirements:
        path: "(\d+|images)/.+"
anu_style_proxy_asset_manager_fetch:
    pattern:  /asset_manager/fetch
    defaults: { _controller: anu_style_proxy.asset_manager_controller:fetchAction }
    requirements:
        _method:  POST
anu_style_proxy_asset_manager_process:
    pattern:  /asset_manager/process
    defaults: { _controller: anu_style_proxy.asset_manager_controller:processAction }
    requirements:
        _method:  POST
