anu_style_proxy_homepage:
    pattern:  /
    defaults: { _controller: anu_style_proxy.default_controller:index }
anu_style_proxy_style_server:
    pattern:  /include.php
    defaults: { _controller: anu_style_proxy.style_server_controller:include }
anu_style_proxy_asset_server:
    pattern:  /{asset_path}
    defaults: { _controller: anu_style_proxy.asset_server_controller:asset }
    requirements:
        asset_path: "(\d+|images)/.+"
anu_style_proxy_asset_manager_fetch:
    pattern:  /asset_manager/fetch
    defaults: { _controller: anu_style_proxy.asset_manager_controller:fetch }
    requirements:
        _method:  POST
anu_style_proxy_asset_manager_process:
    pattern:  /asset_manager/process
    defaults: { _controller: anu_style_proxy.asset_manager_controller:process }
    requirements:
        _method:  POST
