parameters:
    anu_style_proxy.default_controller.class: ANU\Bundle\StyleProxyBundle\Controller\DefaultController
    anu_style_proxy.style_server_controller.class: ANU\Bundle\StyleProxyBundle\Controller\StyleServerController
    anu_style_proxy.asset_server_controller.class: ANU\Bundle\StyleProxyBundle\Controller\AssetServerController
    anu_style_proxy.asset_manager_controller.class: ANU\Bundle\StyleProxyBundle\Controller\AssetManagerController

services:
    anu_style_proxy.default_controller:
        class: %anu_style_proxy.default_controller.class%
    anu_style_proxy.style_server_controller:
        class: %anu_style_proxy.style_server_controller.class%
    anu_style_proxy.asset_server_controller:
        class: %anu_style_proxy.asset_server_controller.class%
    anu_style_proxy.asset_manager_controller:
        class: %anu_style_proxy.asset_manager_controller.class%
