parameters:
    anu_style_proxy.cache.class: ANU\Bundle\StyleProxyBundle\Proxy\Cache
    anu_style_proxy.default_controller.class: ANU\Bundle\StyleProxyBundle\Controller\DefaultController
    anu_style_proxy.style_server_controller.class: ANU\Bundle\StyleProxyBundle\Controller\StyleServerController
    anu_style_proxy.asset_server_controller.class: ANU\Bundle\StyleProxyBundle\Controller\AssetServerController
    anu_style_proxy.asset_manager_controller.class: ANU\Bundle\StyleProxyBundle\Controller\AssetManagerController
    anu_style_proxy.cache_id: liip_doctrine_cache.ns.default

services:
    anu_style_proxy.cache:
        class: %anu_style_proxy.cache.class%
    anu_style_proxy.default_controller:
        class: %anu_style_proxy.default_controller.class%
        calls:
            - [ setContainer, [ @service_container ] ]
    anu_style_proxy.style_server_controller:
        class: %anu_style_proxy.style_server_controller.class%
        calls:
            - [ setContainer, [ @service_container ] ]
    anu_style_proxy.asset_server_controller:
        class: %anu_style_proxy.asset_server_controller.class%
        calls:
            - [ setContainer, [ @service_container ] ]
    anu_style_proxy.asset_manager_controller:
        class: %anu_style_proxy.asset_manager_controller.class%
        calls:
            - [ setContainer, [ @service_container ] ]
