parameters:
    anu_style_proxy.controller.default.class: ANU\Bundle\StyleProxyBundle\Controller\DefaultController
    anu_style_proxy.controller.style_server.class: ANU\Bundle\StyleProxyBundle\Controller\StyleServerController
    anu_style_proxy.controller.asset_server.class: ANU\Bundle\StyleProxyBundle\Controller\AssetServerController
    anu_style_proxy.controller.asset_manager.class: ANU\Bundle\StyleProxyBundle\Controller\AssetManagerController

services:
    anu_style_proxy.default_controller:
        class: %anu_style_proxy.default_controller.class%
    anu_style_proxy.style_server_controller:
        class: %anu_style_proxy.style_server_controller.class%
    anu_style_proxy.asset_server_controller:
        class: %anu_style_proxy.controller.asset_server.class%
    anu_style_proxy.asset_manager_controller:
        class: %anu_style_proxy.controller.asset_manager.class%
