parameters:
    anu_style_proxy.style_server_controller.class: ANU\Bundle\StyleProxyBundle\Controller\StyleServerController

services:
    anu_style_proxy.style_server_controller:
        class: %anu_style_proxy.style_server_controller.class%
        calls:
            - [ setContainer, [ @service_container ] ]
