parameters:
    anu_style_proxy.style_server_controller.class: ANU\Bundle\StyleProxyBundle\Controller\StyleServerController
    anu_style_proxy.style_server.class: ANU\Bundle\StyleProxyBundle\Proxy\StyleServer
    anu_style_proxy.profile_handler.class: ANU\Bundle\StyleProxyBundle\Proxy\Profile\ProfileHandler
    anu_style_proxy.style_server_cache: true
    anu_style_proxy.style_server_cache_lifetime: 2592000  # 30 days
    anu_style_proxy.profile_cache_lifetime: 2592000  # 30 days

services:
    anu_style_proxy.style_server_controller:
        class: %anu_style_proxy.style_server_controller.class%
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ setResponseCache, [ %anu_style_proxy.style_server_cache%, %anu_style_proxy.style_server_cache_lifetime% ] ]
    anu_style_proxy.style_server:
        class: %anu_style_proxy.style_server.class%
        arguments:
            - %anu_style_proxy.backend_style_base%
            - %anu_style_proxy.backend_style_include%
            - @anu_style_proxy.profile_handler
    anu_style_proxy.profile_handler:
        class: %anu_style_proxy.profile_handler.class%
        arguments: [ @anu_style_proxy.cache ]
        calls:
            - [ setCacheLifetime, [ %anu_style_proxy.profile_cache_lifetime% ] ]
            - [ setEventDispatcher, [ @event_dispatcher ] ]
